### ISSUE TITLE
Support Cutter

### ISSUE THREAD

**Issue by XVilka** [yeggor/UEFI_RETool#4]
IDA Pro is not the only reverse engineering platform in the world. Another popular one is [Radare2](https://github.com/radareorg/radare2), a highly-portable cross-platform reverse engineering framework and a toolkit without dependencies. It has support for analyzing binaries, disassembling code, debugging programs, attaching to remote GDB/LLDB, WinDbg servers, rich plugin system (see `r2pm`), and integration with various decompilers. For example, ghidra decompiler plugin - [r2ghidra-dec](https://github.com/radareorg/r2ghidra-dec). It is actively developed and can be easily integrated in various open source and commercial products. I believe, it will be highly beneficial to support these and provide a package for install from `r2pm`, see the package repository here: https://github.com/radareorg/radare2-pm

![image](https://user-images.githubusercontent.com/203261/68269641-7ae24e00-0095-11ea-95f2-cebbc7246954.png)

For documentation on writing plugins for radare2 see [Scripting](https://radare.gitbooks.io/radare2book/content/scripting/intro.html) and [Plugins](https://radare.gitbooks.io/radare2book/content/plugins/intro.html) Radare2 Book chapters.

[Cutter](https://cutter.re/) is a crossplatform Qt/C++ GUI frontend to radare2:

![image](https://user-images.githubusercontent.com/203261/68269343-78332900-0094-11ea-8646-f6226cb6043f.png)

For documentation on writing plugins for Cutter see [the official tutorial](https://cutter.re/docs/plugins.html) and the [curated list](https://github.com/radareorg/cutter-plugins) of various popular plugins.

**Comment by yeggor** [comment]
[analyse_fw_r2.py](https://github.com/yeggor/UEFI_RETool/blob/master/analyse_fw_r2.py) is a r2pipe-based script that allows you to do the same as [analyse_fw_ida.py](https://github.com/yeggor/UEFI_RETool/blob/master/analyse_fw_ida.py)
A plugin for cutter may appear in the future

**Comment by thestr4ng3r** [comment]
Check out https://cutter.re/docs/plugins/tutorial-python.html for info on making cutter plugins

**Comment by krsh** [comment]
@yeggor why have you removed the radare2 support?

**Comment by yeggor** [comment]
I removed the r2pipe-based scripts because they don't work as expected with the latest radare2.
The r2pipe-based scripts are still available here: https://github.com/yeggor/UEFI_RETool/tree/88455f9be1a037d2d20a16cf3b8c9c991b13b2a0, but you probably want to fix them a bit before using.
Most likely, I will bring them up to date to build a dependency graph between UEFI drivers without using IDA Pro.

**Comment by trufae** [comment]
@yeggor Ideally this uefi thing should be packaged into r2pm, for visibility and maintaince, we run tests in radare2-extras to ensure things dont break.

Also, i didnt knew about the existence of it, or didnt tried to use, but overlooking the script i think the problem is related to some changes in the JSON of aflj (offset is now addr), not sure if there are more breaking changes. but it should be easy to spot the other errors. do you have some details about the reason why its not working?

**Comment by yeggor** [comment]
The problem is more likely in the analyzing engine I wrote. I was doing a statistical calculation of the UEFI protocols and services found and found that the script began to find less.
If this script is interesting to the community, I will be happy to update it.
I just verified that the script can still be used (r2 commit: 324a26f5c6290bcfd6d214b1665230d4d542c197).

**Comment by yeggor** [comment]
@trufae @krsh some features from uefi_retool are implemented in [uefi_r2](https://github.com/binarly-io/uefi_r2) (esil based UEFI analyzer):
* search for EFI protocols
* search for EFI GUIDs
* search for Boot Services
* search for Runtime Services

further work is planned on this project
